export interface Song {
  id: number;
  title: string;
  category: string;
  lyrics: string;
  transliteration?: string;
}

export type TabType = 'home' | 'category' | 'fav' | 'info';

/**
 * SpiritualReflection defines the structure of the devotional content 
 * generated by the spiritual reflection service.
 */
export interface SpiritualReflection {
  reflection: string;
  bibleVerse: string;
}
